Repository ppokorni/autoshare_api, pull requests merged in 2022-04, with the labels that each got.

#7 1 user migration model
  app/Models/User.php
  database/migrations/2022_04_08_155216_extend_users_table.php
Labels: core feature

#10 9 add missing registration parameters
  app/Http/Controllers/Api/AuthController.php
  app/Models/User.php
Labels: enhancement

#13 8 user endpoints
  app/Http/Controllers/Api/AuthController.php
  app/Http/Controllers/UserController.php
  app/Http/Resources/UserResource.php
  routes/api.php
Labels: core feature

#14 3 vehicles migration and model
  app/Http/Controllers/Api/VehicleController.php
  app/Models/User.php
  app/Models/Vehicle.php
  app/Models/VehicleFeatures.php
  app/Services/VehicleFeatureService.php
  database/migrations/2022_04_12_192734_create_vehicles_table.php
  database/migrations/2022_04_12_194358_create_vehicle_features_table.php
  routes/api.php
Labels: core feature

#15 11 availability migration and model
  app/Models/Availability.php
  app/Models/Vehicle.php
  database/migrations/2022_04_15_130255_create_availabilities_table.php
Labels: core feature

#18 6 rent migration and model
  app/Models/Availability.php
  app/Models/Rent.php
  database/migrations/2022_04_20_205852_create_rents_table.php
Labels: core feature

#17 Fix users vehicles relation
  app/Models/User.php
Labels: bug
